name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Debug information
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "pyproject.toml contents (if exists):"
        cat pyproject.toml || echo "pyproject.toml not found"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest
    - name: Check formatting
      run: poetry run black --check .
    - name: Check imports
      run: poetry run isort --check-only .
    - name: Type check
      run: poetry run mypy src
    - name: Lint
      run: poetry run flake8 src tests
    - name: Format with Black
      run: poetry run black .
    - name: Check for changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Black made changes. Please run 'black .' locally and commit the changes."
          exit 1
        fi
